version: '3.8'

services:
  radium:
    image: radium:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radium
    volumes:
      - /volume1/docker/radium-data:/home/radium/.radium
    ports:
      - "32349:32349"
    restart: unless-stopped
    environment:
      - PUID=1026  # UID von tars
      - PGID=100   # GID von users